apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample-metrics-app
  labels:
    app: go-sample-metrics-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-sample-metrics-app
  template:
    metadata:
      labels:
        app: go-sample-metrics-app
    spec:
      containers:
        - name: go-sample-metrics-app
          image: ghcr.io/toof-jp/go-sample-metrics-app:sha-bc9e296
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
